USE [gameplanner1]
GO

/****** Object:  Table [dbo].[teams]    Script Date: 4/23/2024 7:25:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[teams](
	[teamId] [int] IDENTITY(1,1) NOT NULL,
	[gameName] [varchar](255) NOT NULL,
	[TeamName] [varchar](255) NOT NULL,
	[noOfParticipants] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[teamId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Teams_TeamName] UNIQUE NONCLUSTERED 
(
	[TeamName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[teams]  WITH CHECK ADD  CONSTRAINT [FK_teams_games] FOREIGN KEY([gameName])
REFERENCES [dbo].[games] ([gameName])
GO

ALTER TABLE [dbo].[teams] CHECK CONSTRAINT [FK_teams_games]
GO


